### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `react-native-svg` from `/home/demo/Documents/icon0.1/icon/assets/icons/git.icon.js`: Module `react-native-svg` does not exist in the Haste module map

### ISSUE THREAD

**Issue by Rananjaya** [AlburIvan/react-native-svg-search#5]
error: bundling failed: Error: Unable to resolve module `react-native-svg` from `/home/demo/Documents/icon0.1/icon/assets/icons/git.icon.js`: Module `react-native-svg` does not exist in the Haste module map

**Comment by AlburIvan** [comment]
Hi Rananjaya,

Did you installed the [react-native-svg](https://github.com/react-native-community/react-native-svg) package and link it?

Can you tell me what version of react, react-native, and react-native-svg you're using ?

Thank you.

**Comment by Rananjaya** [comment]
Yes issue fixed. Thank you.
